accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='account_signup'),
    path('signup/confirm/', views.SignupConfirmView.as_view(), name='account_signup_confirm'),
    path('signup/temporary/', views.SignupDoneView.as_view(), name='account_signup_done'),
    path('signup/thanks/<token>/', views.SignupCompleteView.as_view(), name='account_signup_complete'),
    path('mypage/', views.ProfileView.as_view(), name='profile'),
    path('mypage/email_change/', views.EmailChangeView.as_view(), name='email_change'),
    path('mypage/email_change/send/', views.EmailChangeDoneView.as_view(), name='email_change_done'),
    path('mypage/email_change/done/<str:token>/', views.EmailChangeCompleteView.as_view(), name='email_change_complete'),
    path('mypage/password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('mypage/password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('mypage/delete/confirm', views.DeleteConfirmView.as_view(), name='delete_confirm'),
    path('mypage/delete/done', views.DeleteCompleteView.as_view(), name='delete_complete'),
    path('mypage/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('login/password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('login/password-reset/send/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('login/password-reset/form/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('login/password-reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),
]

app/urls.py
from django.urls import path
from app import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('concept/', views.AboutView.as_view(), name='about'),
    path('order-guide/', views.OrderGuideView.as_view(), name='order_guide'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('addorder/', views.AddOrderView.as_view(), name='add_order'),
    path('deleteorder/', views.DeleteOrderView.as_view(), name='delete_order'),
    path('order/user/', views.OrderUserView.as_view(), name='order_user'),
    path('order/confirm/', views.OrderConfirmView.as_view(), name='order_confirm'),
    path('order/thanks/', views.OrderThanksView.as_view(), name='order_thanks'),
    path('access/', views.AccessView.as_view(), name='access'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('contact/thanks', views.ContactThanksView.as_view(), name='contact_thanks'),
    path('sctl/', views.SctlView.as_view(), name='sctl'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('company/', views.CompanyView.as_view(), name='company'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

admin.site.site_header = 'spoon 管理画面' 
admin.site.index_title = '管理メニュー'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.core.mail import send_mail
from django.utils import timezone


class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


GENDER_CHOICES = (
    ('1', '女性'),
    ('2', '男性'),
)
class CustomUser(AbstractBaseUser, PermissionsMixin):
    name = models.CharField('お名前', max_length=30)
    furigana = models.CharField('フリガナ', max_length=30)
    email = models.EmailField('メールアドレス', max_length=256, unique=True)
    tel = models.CharField('電話番号', max_length=13)
    gender = models.CharField('性別', max_length=2, choices=GENDER_CHOICES, null=True, blank=True)
    birthday = models.DateField('誕生日', null=True, blank=True)

    is_staff = models.BooleanField(
        ('管理サイト使用権限'),
        default=False,
        help_text=('ユーザーがこの管理サイトにログインできるかどうかを指定します。'),
    )
    is_active = models.BooleanField(
        ('アクティブ判定'),
        default=True,
        help_text=(
            'このユーザーをアクティブとして扱うかどうかを指定します。 '
            'アカウントを削除する代わりに、これを選択解除します。'
        ),
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = ('会員一覧')
        verbose_name_plural = ('会員一覧')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from allauth.account.forms import SignupForm
from .models import GENDER_CHOICES
from django.contrib.auth import get_user_model
import datetime
User = get_user_model()


class EmailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class SignupUserForm(SignupForm):
    name = forms.CharField(max_length=30, label='お名前')
    furigana = forms.CharField(max_length=30, label='フリガナ')
    tel = forms.CharField(min_length=10, max_length=13, label='電話番号')
    gender = forms.ChoiceField(
        widget=forms.Select,
        choices=GENDER_CHOICES + (('', '---'),),
        required=False,
        label='性別'
    )
    birthday = forms.DateField(
        widget=forms.SelectDateWidget(
            years=list(reversed([y for y in range(datetime.datetime.now().year - 100, datetime.datetime.now().year)])),
            months={1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12},
        ),
        required=False,
        label='誕生日'
    )


class ProfileForm(forms.Form):
    name = forms.CharField(max_length=30, label='お名前')
    furigana = forms.CharField(max_length=30, label='フリガナ')
    tel = forms.CharField(min_length=10, max_length=13, label='電話番号')
    gender = forms.ChoiceField(
        widget=forms.Select,
        choices=GENDER_CHOICES + (('', '---'),),
        required=False,
        label='性別'
    )
    birthday = forms.DateField(
        widget=forms.SelectDateWidget(
            years=list(reversed([y for y in range(datetime.datetime.now().year - 100, datetime.datetime.now().year)])),
            months={1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12},
        ),
        required=False,
        label='誕生日'
    )


class DeleteForm(forms.Form):
    reason_list = forms.MultipleChoiceField (
        label='退会理由',
        widget=forms.CheckboxSelectMultiple,
        choices= (
            ('メニューの料金が高い', 'メニューの料金が高い'),
            ('メニューに魅力を感じない', 'メニューに魅力を感じない'),
            ('会員特典に魅力を感じない', '会員特典に魅力を感じない'),
            ('サービスが使いにくい', 'サービスが使いにくい'),
            ('他にもっと良いサービスを見つけた', '他にもっと良いサービスを見つけた'),
        )
    )
    message = forms.CharField(label='その他', widget=forms.Textarea(), required=False)

accounts/templates/accounts/delete_complete.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>退会完了 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>退会</span>
</h1>

<div class="text-center mb-4">
    <img class="done-check" src="{% static 'img/check.svg' %}">
</div>
<div class="mx-auto text-center">
    <p class="done-text">退会手続きを完了しました。</p><br>
    <p class="d-inline-block text-left">
        退会手続き完了のメールをお送りさせていただきましたので、内容をご確認ください。<br>
        ご利用ありがとうございました。<br>
        またの機会のご利用、心よりお待ちしております。
    </p>
</div>

<div class="text-center">
    <a class="delete__form--btn btn rounded-pill" href="/" ontouchstart="">トップページに戻る</a>
</div>
{% endblock %}

accounts/templates/accounts/delete_confirm.html
{% extends "app/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
<title>退会確認 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>退会</span>
</h1>

<div class="text-center mb-4">
    <img class="done-check" src="{% static 'img/delete.svg' %}">
</div>

<div class="mx-auto text-center m-0">
    <p class="delete__text d-inline-block text-left mb-5">退会手続きを実行します。</p><br>
    <p class="d-inline-block text-left">
        これまでspoonの会員サービスをご利用いただき、誠にありがとうございました。<br>
        spoonではお客様により良いサービスを提供できるよう努めております。<br>
        率直なご意見・ご要望をお聞かせください。<br>
    </p>
    <form method="POST" class="delete__form text-center">
        {% csrf_token %}
        <table class="delete__form--table d-table mx-auto card p-4 p-sm-3">
            <tbody class="delete__form--table--body mx-auto">
                <tr class="d-block d-sm-table-row">
                    <th class="d-block d-sm-table-cell text-left align-top mb-2 mb-sm-0">
                        <label class="m-0">退会理由
                            <span class="signup__required">【必須】</span>
                            <span class="help-text font-weight-normal">※複数選択可</span>
                        </label>
                    </th>
                    <td class="d-block d-sm-table-cell mb-4">
                        {% for reason in form.reason_list %}
                            <p class="text-left mb-1">{{ reason }}</p>
                        {% endfor %}
                        <p class="error-msg text-left m-0">
                            {{ error }}
                        </p>
                    </td>
                </tr>
                <tr class="d-block d-sm-table-row">
                    <th class="d-block d-sm-table-cell text-left align-top">
                        <label for="id_message" class="m-0">その他
                            <span class="font-weight-normal">【※任意】</span>
                        </label>
                    </th>
                    <td class="d-block d-sm-table-cell">
                        {% render_field form.message class="form-control" placeholder="自由記入欄" %}
                    </td>
                </tr>
            </tbody>
        </table>
        <p class="mt-5">
            下記ボタンを押すと<br class="d-sm-none">退会手続きを実行します。<br>
            本当によろしいですか？
        </p>
        <button type="submit" class="delete__form--btn btn rounded-pill mt-3" ontouchstart="">はい、退会します</button><br>
        <button type="button" class="deleteno__btn btn rounded-pill mt-4" onclick="history.back()" ontouchstart="">いいえ、退会しません</button>
    </form>
</div>
{% endblock %}


{% block extrajs %}
<script>
    'use strict'

    // 注意事項のアラート
    const element  = Object.assign(document.createElement('div'), { className: 'delete__alert sticky-top rounded-0 alert alert-danger alert-dismissible fade show m-0' });
    const element1  = Object.assign(document.createElement('strong'), { className: 'alert-heading', innerHTML: '<i class="fas fa-exclamation-triangle fa-fw mr-1" aria-hidden="true"></i>注意事項' });
    const element2  = Object.assign(document.createElement('p'), { className: 'delete__alert--text mt-1 mb-0', innerHTML: '退会するとお客様の情報はすべて削除され、会員情報は元に戻せません。<br>短期間に再登録を複数回行うことは禁じております。あらかじめご了承くださいませ。' });
    const element3  = Object.assign(document.createElement('button'), { className: 'delete__alert--btn close', type: 'button' });
    const element4  = Object.assign(document.createElement('span'), { className: 'delete__alert--close', innerHTML: '&times;' });
    // 階層に合わせて要素をまとめる
    element3.appendChild(element4);
    element.appendChild(element1);
    element.appendChild(element2);
    element.appendChild(element3);
    // 最後に追加
    document.body.insertBefore(element, document.body.firstChild);

    let deleteAlert = document.querySelector('.delete__alert');
    deleteAlert.setAttribute('role', 'alert');
    let alertBtn = document.querySelector('.delete__alert--btn');
    alertBtn.setAttribute('data-dismiss', 'alert');
    alertBtn.setAttribute('aria-label', 'Close');
    let alertClose = document.querySelector('.delete__alert--close');
    alertClose.setAttribute('aria-hidden', 'true');

    // エラーメッセージ解除
    let reason = document.getElementsByName('reason_list');
    for (let i = 0; i < reason.length; i++) {
        reason[i].addEventListener('click', () => {
            document.querySelector('.error-msg').classList.add('d-none');
        })
    }
</script>
{% endblock %}

accounts/templates/accounts/email_change_done.html
{% extends "app/base.html" %}

{% block title %}
<title>メールアドレス変更確認 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span class="px-3">メールアドレス変更</span>
</h1>

<div class="mx-auto text-center">
    <p class="d-inline-block text-left m-0">
        新しいメールアドレスに確認用メールを送信しました。まだ変更手続きは完了していません。<br>
        メール本文に記載のURLにアクセスして手続きを完了してください。<br><br>
        <span class="help-text">※当店からのメールが届かない場合は入力情報、メール設定をご確認ください。</span>
    </p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "app/base.html" %}

{% block title %}
<title>パスワードリセット確認 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span class="px-2">パスワードリセット</span>
</h1>

<div class="mx-auto text-center">
    <p class="d-inline-block text-left m-0">
        パスワード再設定用のメールを送信しました。<br>
        メール本文に記載のURLから再設定手続きを行ってください。<br><br>
        <span class="help-text">※当店からのメールが届かない場合は入力情報、メール設定をご確認ください。</span>
    </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "app/base.html" %}
{% load humanize %}

{% block title %}
<title>マイページ | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>プロフィール</span>
</h1>

<div class="profile mx-auto">
    <table class="profile__table">
        <tbody>
            <tr class="d-block d-sm-table-row">
                <th class="d-block d-sm-table-cell text-center text-sm-left py-1 py-sm-3 px-4">お名前</th>
                <td class="d-block d-sm-table-cell text-center text-sm-left py-3 px-4">{{ user_data.name }}</td>
            </tr>
            <tr class="d-block d-sm-table-row">
                <th class="d-block d-sm-table-cell text-center text-sm-left py-1 py-sm-3 px-4">フリガナ</th>
                <td class="d-block d-sm-table-cell text-center text-sm-left py-3 px-4">{{ user_data.furigana }}</td>
            </tr>
            <tr class="d-block d-sm-table-row">
                <th class="d-block d-sm-table-cell text-center text-sm-left py-1 py-sm-3 px-4">メールアドレス</th>
                <td class="profile__table--email d-block d-sm-table-cell text-center text-sm-left py-3 px-4 overflow-auto">{{ user_data.email }}</td>
            </tr>
            <tr class="d-block d-sm-table-row">
                <th class="d-block d-sm-table-cell text-center text-sm-left py-1 py-sm-3 px-4">電話番号</th>
                <td class="d-block d-sm-table-cell text-center text-sm-left py-3 px-4">{{ user_data.tel }}</td>
            </tr>
            <tr class="d-block d-sm-table-row">
                <th class="d-block d-sm-table-cell text-center text-sm-left py-1 py-sm-3 px-4">性別</th>
                <td id="gender" class="d-block d-sm-table-cell text-center text-sm-left py-3 px-4">{{ user_data.get_gender_display }}</td>
            </tr>
            <tr class="d-block d-sm-table-row">
                <th class="d-block d-sm-table-cell text-center text-sm-left py-1 py-sm-3 px-4">誕生日</th>
                <td id="birthday" class="d-block d-sm-table-cell text-center text-sm-left py-3 px-4">{{ user_data.birthday }}</td>
            </tr>
        </tbody>
    </table>
    <div class="profile__link text-left">
        <a class="profile__link--text mt-1" href="{% url 'email_change' %}">メールアドレスの変更手続きはこちら</a><br>
        <a class="profile__link--text mt-1" href="{% url 'password_change' %}">パスワードの変更手続きはこちら</a><br>
        <a class="profile__link--text mt-1" href="{% url 'delete_confirm' %}">会員サービスの退会手続きはこちら</a>
    </div>
    <div class="text-center">
        <a class="profile__btn btn rounded-pill mb-5" href="{% url 'profile_edit' %}" ontouchstart="">
            <i class="fas fa-edit fa-fw" aria-hidden="true"></i>編集
        </a>
    </div>
</div>

<h1 class="title mt-5">
    <span>注文履歴</span>
</h1>

{% for order in order_data %}
{% if forloop.last %}
<div class="history card mx-auto">
{% else %}
<div class="history card mx-auto mb-5">
{% endif %}
    <div class="history__header card-header p-0">
        <div class="d-flex flex-column flex-sm-row align-items-center justify-content-between">
            <div class="d-md-flex pt-4 px-3 pt-sm-3 py-sm-3">
                <div class="history__header--wrap d-flex flex-md-column mr-md-4 mr-lg-5">
                    <span class="history__header--wrap--orderday mr-3 mr-md-0">注文日時</span>
                    <span>{{ order.created | date:"Y年n月j日(l) G:i" | cut:"曜日" }}</span>
                </div>
                <div class="history__header--wrap d-flex flex-md-column mr-md-4 mr-lg-5">
                    <span class="history__header--wrap--orderday mr-3 mr-md-0">受取日時</span>
                    <span>{{ order.receipt | date:"Y年n月j日(l) G:i" | cut:"曜日" }}</span>
                </div>
                {% if order.coupon_price != 0 %}
                    <div class="history__header--wrap d-flex flex-md-column mr-md-4 mr-lg-5">
                        <span class="history__header--wrap--orderday mr-3 mr-md-0">クーポン</span>
                        <span class="history__header--wrap--coupon">-&yen;{{ order.coupon_price }}</span>
                    </div>
                {% endif %}
                <div class="history__header--wrap d-flex flex-md-column">
                    <span class="history__header--wrap--orderday mr-3 mr-md-0 mr-md-0">合計　　</span>
                    <span>&yen;{{ order.get_total | intcomma }}</span>
                </div>
            </div>
            <button type="button" id="{{ order.id }}" class="history__header--btn mt-0 mb-4 my-sm-0 mr-sm-3 p-sm-3 p-md-2 btn" onclick="sameOrder(this);" ontouchstart="">再度注文</button>
        </div>
    </div>
    {% for cart in order.cart.all %}
        <div class="row p-0 m-4">
            <div class="col-sm-8 col-md-7 mb-3 mb-sm-0 p-0">
                <div class="d-flex justify-content-center justify-content-sm-start align-items-end">
                    <div class="d-flex mr-2">
                        <img class="history__size-img" src="{{ cart.size_image.url }}">
                    </div>
                    <div class="d-flex mr-2">
                        <img class="history__flavor-img" src="{{ cart.flavor_image.url }}">
                    </div>
                    {% if cart.flavor2_title != '' %}
                        <img class="history__flavor-img" src="{{ cart.flavor2_image.url }}">
                    {% endif %}
                </div>
                <div class="d-flex justify-content-center justify-content-sm-start mt-2 mt-sm-3">
                    {% if cart.option_title != '' %}
                        <img class="history__option-img mr-2" src="{{ cart.option_image.url }}">
                    {% endif %}
                    {% if cart.option2_title != '' %}
                        <img class="history__option-img mr-2" src="{{ cart.option2_image.url }}">
                    {% endif %}
                    {% if cart.option3_title != '' %}
                        <img class="history__option-img mr-2" src="{{ cart.option3_image.url }}">
                    {% endif %}
                    {% if cart.option4_title != '' %}
                        <img class="history__option-img" src="{{ cart.option4_image.url }}">
                    {% endif %}
                </div>
            </div>
            <table class="history__table col-sm-4 col-md-5 p-0">
                <tbody>
                    <tr class="d-sm-block d-md-table-row">
                        <th class="d-sm-block d-md-table-cell">【サイズ】</th>
                        <td class="d-sm-block d-md-table-cell">{{ cart.size_title }}</td>
                    </tr>
                    <tr class="d-sm-block d-md-table-row">
                        <th class="align-top d-sm-block d-md-table-cell">【フレーバー】</th>
                        <td class="d-sm-block d-md-table-cell">{{ cart.flavor_title }}<br>{{ cart.flavor2_title }}</td>
                    </tr>
                    <tr class="d-sm-block d-md-table-row">
                        <th class="align-top d-sm-block d-md-table-cell">【オプション】</th>
                        {% if cart.option_title == "" and cart.option2_title == "" and cart.option3_title == "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">なし</td>
                        {% elif cart.option_title != "" and cart.option2_title == "" and cart.option3_title == "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title != "" and cart.option3_title == "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option2_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title == "" and cart.option3_title != "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option3_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title == "" and cart.option3_title == ""  and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option4_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title != "" and cart.option3_title == "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option2_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title == "" and cart.option3_title != "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option3_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title == "" and cart.option3_title == "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option4_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title != "" and cart.option3_title != "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option2_title }}<br>{{ cart.option3_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title != "" and cart.option3_title == "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option2_title }}<br>{{ cart.option4_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title == "" and cart.option3_title != "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option3_title }}<br>{{ cart.option4_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title != "" and cart.option3_title != "" and cart.option4_title == "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option2_title }}<br>{{ cart.option3_title }}</td>
                        {% elif cart.option_title == "" and cart.option2_title != "" and cart.option3_title != "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option2_title }}<br>{{ cart.option3_title }}<br>{{ cart.option4_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title == "" and cart.option3_title != "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option3_title }}<br>{{ cart.option4_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title != "" and cart.option3_title == "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option2_title }}<br>{{ cart.option4_title }}</td>
                        {% elif cart.option_title != "" and cart.option2_title != "" and cart.option3_title != "" and cart.option4_title != "" %}
                            <td class="d-sm-block d-md-table-cell">{{ cart.option_title }}<br>{{ cart.option2_title }}<br>{{ cart.option3_title }}<br>{{ cart.option4_title }}</td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        </div>
        {% if not forloop.last %}
            <hr class="history__border mx-4 my-0">
        {% endif %}
    {% endfor %}
</div>
{% if forloop.last %}
    <p class="history__comment help-text d-block mx-auto mt-2">※現在価格はご注文当時から変更となっている場合がございます。<br>※現在お取り扱いの無い商品が含まれる場合には再注文いたしかねます。ご了承ください。</p>
{% endif %}
{% empty %}
    <p class="text-center">現在ご注文履歴はありません。<br>ぜひお買い物をお楽しみください。</p>
{% endfor %}
{% endblock %}


{% block extrajs %}
<script>
    'use strict';

    // 性別がNoneの場合は空白表示
    const gender = document.getElementById('gender');
    if ( gender.textContent == 'None') {
        gender.textContent = '';
    }

    // 誕生日がNoneの場合は空白表示
    const birthday = document.getElementById('birthday');
    if ( birthday.textContent == 'None') {
        birthday.textContent = '';
    }

    // CSRF対策
    const getCookie = name => {
        if (document.cookie && document.cookie !== '') {
            for (const cookie of document.cookie.split(';')) {
                const [key, value] = cookie.trim().split('=');
                if (key === name) {
                    return decodeURIComponent(value);
                }
            }
        }
    };
    const csrftoken = getCookie('csrftoken');

    // 再注文処理
    const sameOrder = (ele) => {
        let id_value = ele.id;
        var element = document.getElementById(id_value);

        const url = '{% url "profile" %}';
        // URLのクエリパラメータを管理
        const body = new URLSearchParams();
        body.append('id_value', id_value);

        fetch(url, {
            method: 'POST',
            body: body,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'X-CSRFToken': csrftoken,
            }
        }).then(response => {
            // JSON形式に変換
            return response.json();
        }).then(response => {
            // 再注文OKならばオーダー画面へ
            if ( response.error.length == 0 ) {
                window.location.href = '{% url "order" %}';
            // 再注文NGならば案内画面へ
            } else {
                let none_item = response.error.join('・');
                window.location.href = '{% url "order" %}?msg=' + none_item
            }
        })
    }
</script>
{% endblock %}