app/urls.py
from django.urls import path
from app import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('concept/', views.AboutView.as_view(), name='about'),
    path('order-guide/', views.OrderGuideView.as_view(), name='order_guide'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('addorder/', views.AddOrderView.as_view(), name='add_order'),
    path('deleteorder/', views.DeleteOrderView.as_view(), name='delete_order'),
    path('order/user/', views.OrderUserView.as_view(), name='order_user'),
    path('order/confirm/', views.OrderConfirmView.as_view(), name='order_confirm'),
    path('order/thanks/', views.OrderThanksView.as_view(), name='order_thanks'),
    path('access/', views.AccessView.as_view(), name='access'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('contact/thanks', views.ContactThanksView.as_view(), name='contact_thanks'),
    path('sctl/', views.SctlView.as_view(), name='sctl'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('company/', views.CompanyView.as_view(), name='company'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

admin.site.site_header = 'spoon 管理画面' 
admin.site.index_title = '管理メニュー'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3


class ReceiptForm(forms.Form):
    name = forms.CharField(max_length=30, label='お名前')
    furigana = forms.CharField(max_length=30, label='フリガナ')
    email = forms.EmailField(min_length=7, max_length=256, label='メールアドレス')
    tel = forms.CharField(min_length=10, max_length=13, label='電話番号')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=30, label='お名前')
    email = forms.EmailField(min_length=7, max_length=256, label='メールアドレス')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea())
    captcha = ReCaptchaField(widget=ReCaptchaV3)

app/templates/app/about.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>spoonについて | spoon</title>
{% endblock %}

{% block content %}
<div class="row px-3">
    <div class="col-xl-9 p-0">
        <h1 class="title">
            <span>spoonについて</span>
        </h1>
        <div class="about row justify-content-center">
            <div class="col-sm-10 col-md-6 col-lg-5 col-xl-6 about__fadein">
                <img class="w-100" src="{% static 'img/about1.png' %}">
            </div>
            <div class="col-sm-10 col-md-6 col-lg-7 col-xl-6">
                <h2 class="about__subheading mt-3 mt-md-0 about__fadein">手づくりジェラート専門店</h2>
                <p class="about__msg about__fadein">spoonのジェラートを口に入れた瞬間、ほわっと、ふんわりした舌ざわりとともに、素材の味が香り豊かに広がります。それぞれに使用する材料や配合、甘さのバランスにもとことんこだわり、さっぱりした後味もその魅力の一つ。お客様のもっと食べたい！また食べたい！を目指して、他のジェラートとは違うspoonならではの味を追求しています。</p>
            </div>
        </div>
        <div class="about row justify-content-center">
            <div class="col-sm-10 col-md-6 col-lg-7 col-xl-6 order-2 order-md-1">
                <h2 class="about__subheading mt-3 mt-md-0 about__fadein">30種類以上のオリジナルフレーバー</h2>
                <p class="about__msg about__fadein">見た目でも楽しむことのできるspoonのジェラート。お店に入ると色鮮やかに並ぶたくさんのジェラートに驚かれることでしょう。そんなワクワク感と選ぶ楽しみもご提供したく、現在は30種類以上のジェラートを取り揃えております（季節限定含む）。<a href="{% url 'order_guide' %}">spoonのお持ち帰り予約</a>でご注文いただくと、WEB限定フレーバーも含めて全種類お楽しみいただけます。ぜひ自分好みのフレーバーを見つけてみてください。</p>
            </div>
            <div class="col-sm-10 col-md-6 col-lg-5 col-xl-6 flex-first order-1 order-md-2 about__fadein">
                <img class="w-100" src="{% static 'img/about2.png' %}">
            </div>
        </div>
        <div class="about row justify-content-center">
            <div class="col-sm-10 col-md-6 col-lg-5 col-xl-6 about__fadein">
                <img class="w-100" src="{% static 'img/about3.png' %}">
            </div>
            <div class="col-sm-10 col-md-6 col-lg-7 col-xl-6 mb-0">
                <h2 class="about__subheading mt-3 mt-md-0 about__fadein">ご自宅でも楽しめるspoonジェラート</h2>
                <p class="about__msg about__fadein">大切な方への手みやげに、一つ一つ丁寧に手づくりしたジェラートはいかがでしょう？お店で選び、その場で食べることもジェラートショップならではの楽しみ方ですが、その美味しさをお持ち帰りしたいとのお声もいただきます。<a href="{% url 'order_guide' %}">spoonのお持ち帰り予約</a>でご注文いただけば、お持ち帰りでも口あたりなめらかな、ひんやりジェラートをご提供できます。ぜひお試しください。</p>
            </div>
        </div>
        <p class="help-text px-3">※写真はすべてイメージです。spoonのお持ち帰り予約サービスのご利用には<a href="{% url 'account_signup' %}">無料会員登録</a>が必要です。</p>
    </div>
    {% include 'app/sidebar.html' %}
</div>
{% endblock %}


{% block extrajs %}
<script>
    'use strict';

    animation('.about__fadein');
    // スクロールで発動
    window.addEventListener('scroll', () => {
        animation('.about__fadein');
    });
</script>
{% endblock %}

app/templates/app/access.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>アクセス | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>アクセス</span>
</h1>

<div class="access row justify-content-center m-0">
    <img class="access__map card col-lg-7 p-0 h-100" src="{% static 'img/spoon_map.svg' %}">
    <div class="access__info col-lg-5 pl-0 pl-lg-4 pt-5 pt-lg-0 pr-0">
        <p class="access__info--name ml-lg-3 mb-5 text-center text-lg-left">
            <span class="access__info--name--e mr-2">spoon</span>
            ジェラート＆焼菓子
        </p>
        <table class="access__info--table mx-auto">
            <tbody>
                <tr>
                    <th class="pl-4">住所</th>
                    <td class="pl-4 pr-3">
                        <a class="access__info--table--map" href="https://www.google.co.jp/maps/place/%E3%80%92370-3522+%E7%BE%A4%E9%A6%AC%E7%9C%8C%E9%AB%98%E5%B4%8E%E5%B8%82%E8%8F%85%E8%B0%B7%E7%94%BA%EF%BC%91%EF%BC%92%EF%BC%94%EF%BC%93%E2%88%92%EF%BC%99/@36.3803438,139.0080042,17z/data=!3m1!4b1!4m5!3m4!1s0x601e8c8d4e95f6e7:0x5882f4339e9e0814!8m2!3d36.3803395!4d139.0101929?hl=ja">群馬県高崎市菅谷町1243-10</a>
                    </td>
                </tr>
                <tr>
                    <th class="pl-4">電話番号</th>
                    <td class="pl-4">027-310-0112</td>
                </tr>
                <tr>
                    <th class="pl-4">営業時間</th>
                    <td class="access__info--table--time pl-4 py-3">
                        12:30～17:30
                        <!-- 平　日　12:30～17:30<br> -->
                        <!-- 土日祝　11:00～18:00 -->
                        <span class="access__info--table--time--help help-text">※材料が終わり次第、営業終了になることもございます。</span>
                    </td>
                </tr>
                <tr>
                    <th class="pl-4">定休日</th>
                    <td class="pl-4">不定休</td>
                </tr>
                <tr>
                    <th class="pl-4">駐車場</th>
                    <td class="pl-4">あり（5台）</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/app/company.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>会社概要 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>会社概要</span>
</h1>

<table class="company mx-auto">
    <tbody>
        <tr>
            <th class="px-2 py-4 p-sm-4">社名</th>
            <td class="px-2 py-4 p-sm-4">有限会社プラリネ</td>
        </tr>
        <tr>
            <th class="px-2 py-4 p-sm-4 align-top">所在地</th>
            <td class="px-2 py-4 p-sm-4">〒370-0074<br class="d-sm-none">
                <span class="ml-sm-3">群馬県高崎市下小鳥町67番地5</span>
            </td>
        </tr>
        <tr>
            <th class="px-2 py-4 p-sm-4">電話番号</th>
            <td class="px-2 py-4 p-sm-4">027-363-8258</td>
        </tr>
        <tr>
            <th class="px-2 py-4 p-sm-4">代表取締役</th>
            <td class="px-2 py-4 p-sm-4">細谷和利</td>
        </tr>
        <tr>
            <th class="px-2 py-4 p-sm-4">設立</th>
            <td class="px-2 py-4 p-sm-4">2000年1月</td>
        </tr>
        <tr>
            <th class="px-2 py-4 p-sm-4">資本金</th>
            <td class="px-2 py-4 p-sm-4">300万円</td>
        </tr>
        <tr>
            <th class="px-2 py-4 p-sm-4 align-top">事業内容</th>
            <td class="px-2 py-4 p-sm-4">パンの製造・販売、カフェ経営、ジェラート店経営</td>
        </tr>
    </tbody>
</table>
{% endblock %}

app/templates/app/contact_thanks.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>お問い合わせ完了 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>お問い合わせ</span>
</h1>

<div class="text-center mb-4">
    <img class="done-check" src="{% static 'img/check.svg' %}">
</div>
<div class="mx-auto text-center">
    <p class="done-text">お問い合わせを<br class="d-sm-none">受け付けました。</p><br>
    <p class="d-inline-block text-left">
        お問い合わせ内容につきましては、通常3営業日程度を目処にご回答させていただきます。<br>
        恐れ入りますが、しばらくお待ちくださいませ。<br><br>
        なお、ご入力いただいたメールアドレス宛に受付確認メールをお送りしております。<br>
        確認メールが届かない場合、メールアドレスが誤っているか、<br>
        確認メールが迷惑メールフォルダ等に振り分けられている可能性がありますので、<br class="d-none d-md-block">
        再度ご確認をお願いいたします。<br><br>
        今後ともご愛顧賜りますよう、よろしくお願い申し上げます。
    </p>
</div>

<div class="text-center">
    <a class="contact__form--btn btn rounded-pill" href="/" ontouchstart="">トップページに戻る</a>
</div>
{% endblock %}

app/templates/app/menu.html
{% extends "app/base.html" %}

{% block title %}
<title>商品メニュー | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>商品メニュー</span>
</h1>

<div class="menu mx-auto text-center">
    <p class="d-inline-block text-left mb-5">
        フレッシュな旬のフルーツを中心に、旬の素材をたっぷりと使ったspoonジェラート。<br>
        素材の味を活かし、あっさりした味わいや濃厚な味わいのジェラートまで常時20種類をご用意しています。
    </p>
    <div class="menu__item mx-auto text-center">
        <p class="menu__flavor-type d-inline-block mb-4">人気の定番フレーバー</p>
    </div>
    <ul class="row list-unstyled">
        {% for flavor in flavor_item %}
            <li class="menu__item col-4 col-sm-3 col-lg-2 mb-4 px-2 px-sm-4">
                <div>
                    <img class="menu__item--img mb-2" src="{{ flavor.image.url }}">
                    <p class="menu__item--name text-left m-0">
                        {% if flavor.price > 0 %}&#9733;{% endif %}{{ flavor.title }}
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div class="menu__item mx-auto text-center">
        <p class="menu__flavor-type d-inline-block mb-4">WEB限定フレーバー</p>
    </div>
    <ul class="row list-unstyled">
        {% for flavor in flavor_web %}
            <li class="menu__item col-4 col-sm-3 col-lg-2 mb-4 px-2 px-sm-4">
                <div>
                    <img class="menu__item--img mb-2" src="{{ flavor.image.url }}">
                    <p class="menu__item--name text-left m-0">
                        {% if flavor.price > 0 %}&#9733;{% endif %}{{ flavor.title }}
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div class="d-md-flex justify-content-between mt-5">
        <div>
            <ul class="menu__item--type d-flex justify-content-sm-center list-unstyled m-0">
                {% for size in size_item %}
                    <li class="d-flex flex-column flex-lg-row align-items-center text-left mr-sm-5 mr-lg-4">
                        <span class="menu__item--type--name mb-1 mb-sm-0 mr-lg-2">
                            {% if forloop.counter == 1 %}
                                M:ミニ
                            {% elif forloop.counter == 2 %}
                                S:シングル
                            {% elif forloop.counter == 3 %}
                                W:ダブル
                            {% endif %}
                        </span>
                        <span class="menu__item--type--price">&yen;{{ size.price }}</span>
                    </li>
                {% endfor %}
            </ul>
            <p class="help-text d-sm-block text-left text-sm-center text-md-left m-0 mt-1">※★が付いているメニューは、金額がプラスになります。</p>
        </div>
        <div>
            <a class="menu__btn btn m-md-0 rounded-pill" href="{% url 'order' %}" ontouchstart="">お持ち帰り注文はコチラ</a>
        </div>
    </div>
    <p class="menu__baked text-left text-md-center p-2 px-md-0 mb-0">店頭ではグラノーラやクッキーなどの手づくり焼菓子も販売しております。ぜひご賞味ください！</p>
</div>
{% endblock %}


{% block extrajs %}
<script>
    'use strict'

    animation('.menu__item');
    // スクロールで発動
    window.addEventListener('scroll', () => {
        animation('.menu__item');
    });
</script>
{% endblock %}

app/templates/app/order_thanks.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>お持ち帰り予約 - 注文完了 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>お持ち帰り予約</span>
</h1>

<div class="text-center mb-4">
    <img class="done-check" src="{% static 'img/check.svg' %}">
</div>

<div class="class mx-auto text-center">
    <p class="done-text text-center">ご注文いただき、<br class="d-sm-none">ありがとうございます。</p><br>
    <p class="d-inline-block text-left">
        ご注文内容の確認メールをお送りさせていただきました。<br>
        メール本文記載の注文番号を店頭にてご提示ください。<br>
        店頭にて商品をご用意してお待ちしております。<br><br>
        今後ともご愛顧賜りますよう、よろしくお願い申し上げます。
    </p>
</div>

<div class="text-center">
    <a class="order-ck__btn btn rounded-pill" href="/">トップページに戻る</a>
</div>
{% endblock %}

app/templates/app/order_user.html
{% extends "app/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
<title>お持ち帰り予約 - 注文情報 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span>お持ち帰り予約</span>
</h1>

<div class="mx-auto text-center">
    <p class="d-inline-block text-left mb-4">ご注文様の情報とお受け取り日時をご入力ください。</p>
    <form method="POST" action="{% url 'order_confirm' %}" class="text-center">
        {% csrf_token %}
        <table class="order-user__form d-table card mx-auto p-4 p-md-3 ">
            <tbody class="order-user__form--body mx-auto">
                <tr class="d-block d-md-table-row">
                    <th class="d-block d-md-table-cell text-left text-md-right align-top">
                        <label for="id_name" class="m-0">お名前
                            <span class="signup__required">【必須】</span>
                        </label>
                    </th>
                    <td class="d-block d-md-table-cell mb-4">
                        {% render_field form.name class="form-control" %}
                    </td>
                </tr>
                <tr class="d-block d-md-table-row">
                    <th class="d-block d-md-table-cell text-left text-md-right align-top">
                        <label for="id_furigana" class="m-0">フリガナ
                            <span class="signup__required">【必須】</span>
                        </label>
                    </th>
                    <td class="d-block d-md-table-cell mb-4">
                        {% render_field form.furigana class="form-control" %}
                    </td>
                </tr>
                <tr class="d-block d-md-table-row">
                    <th class="d-block d-md-table-cell text-left text-md-right align-top">
                        <label for="id_email" class="m-0">メールアドレス
                            <span class="signup__required">【必須】</span>
                        </label>
                    </th>
                    <td id="email-form" class="d-block d-md-table-cell mb-4">
                        {% render_field form.email class="form-control" placeholder="メールアドレス" %}
                        {% for field in form %}
                            <p class="error-msg email_error d-none text-left m-0">
                                {% for error in field.errors %}
                                    ※{{ error }}<br>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <p class="error-msg email_error d-none text-left m-0">
                                ※{{ error }}
                            </p>
                        {% endfor %}
                    </td>
                </tr>
                <tr class="d-block d-md-table-row">
                    <th class="d-block d-md-table-cell text-left text-md-right align-top">
                        <label for="id_tel" class="m-0">電話番号
                            <span class="signup__required">【必須】</span>
                        </label>
                    </th>
                    <td class="d-block d-md-table-cell mb-4">
                        {% render_field form.tel class="form-control" %}
                    </td>
                </tr>
                <tr class="d-block d-md-table-row">
                    <th class="d-block d-md-table-cell text-left text-md-right align-top">
                        <label class="m-0">受取日時
                            <span class="signup__required">【必須】</span>
                        </label>
                    </th>
                    <td class="d-block mb-4">
                        <div class="d-sm-flex">
                            <select id="date" name="date" class="order-user__form--body--select--date form-control mb-2 mb-sm-0 mr-sm-3" onchange="timeChange();">
                                {% for date in date_list %}
                                    <option value="{{ date }}">{{ date }}</option>
                                {% endfor %}
                            </select>
                            <select id="specified_time" name="time" class="order-user__form--body--select--time form-control">
                                {% for time in time_list %}
                                    <option value="{{ time }}">{{ time }}</option>
                                {% endfor %}
                            </select>
                            <select id="full_time" name="fulltime" class="order-user__form--body--select--time d-none form-control">
                                {% for fulltime in fulltime_list %}
                                    <option value="{{ fulltime }}">{{ fulltime }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <p class="error-msg text-left mt-1 mb-0">※10月は毎週月・火曜日（祝日を除く）をお休みさせていただきます。</p>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="order-user__help mx-auto mt-1">
            <p class="help-text text-left m-0">
                ※当日のご注文受付は16:30までとさせていただきます。また店舗の状況により当日注文をお受けいたしかねる場合がございます。ご了承ください。※16:30以降にご注文の場合は翌日13:00以降のお受け取りとなります。
            </p>
        </div>
        <div class="position-relative">
            <a class="back-btn d-none d-sm-block btn rounded-pill" href="{% url 'order' %}" ontouchstart="">戻る</a>
            <button class="order-user__btn btn rounded-pill" type="submit" ontouchstart="">注文確認画面へ</button>
        </div>
    </form>
</div>
{% endblock %}


{% block extrajs %}
<script>
    'use strict';

    // 本日を選択時のみ指定時間に変更
    let date = document.getElementById('date');
    let specified_time = document.getElementById('specified_time');
    let fulltime = document.getElementById('full_time');

    let timeChange = () => {
        if (date.value.match(/本日/)) {
            specified_time.className = 'order-user__form--body--select--time d-block form-control';
            full_time.className = 'd-none';
        } else {
            specified_time.className = 'd-none';
            full_time.className = 'order-user__form--body--select--time d-block form-control';
        }
    }

    // エラーメッセージ（メールアドレス）
    const email_error = document.querySelectorAll('.email_error');
    const email = document.getElementById('id_email');
    for ( let i = 0; i < email_error.length; i++ ) {
        if ( email_error[i].textContent.match(/メール/) ) {
            email_error[i].className = 'error-msg m-0 d-block text-left';
            email.className = 'form-control form-error';
        }
        email.addEventListener('click', () => {
            email_error[i].className = 'error-msg email_error d-none m-0 text-left'
            email.className = 'form-control'
        })
    }

    // リアルタイムバリデーション
    email.oninput = () => {
        const emailForm = document.getElementById('email-form');
        let settingInfo = (link, carrier)  => {
            const element  = Object.assign(
                document.createElement('p'), {
                    className: 'order-user__form--body--email-warning text-left mt-1 mb-0',
                    innerHTML: `<i class="order-user__form--body--email-warning--icon fas fa-exclamation-triangle fa-fw mr-1" aria-hidden="true"></i>\
                        ご注文確認メールが「spoon.gelato.takasaki@gmail.com」から届きます。<br>\
                        <b>受信許可設定（迷惑メール設定）</b>はお済みですか？\
                        <a class="order-user__form--body--email-warning--detail" href=${link} target="_blank" rel="noopener">${carrier}</a>`
                }
            );
            emailForm.insertBefore(element, email.nextSibling);
        }
        if ( email.value.match(/ezweb.ne.jp/) && emailForm.children.length == 5 ) {
            settingInfo('https://www.au.com/support/service/mobile/trouble/mail/email/filter/detail/domain/', 'au受信リスト設定');
        } else if ( email.value.match(/softbank.jp/) && emailForm.children.length == 5 ) {
            settingInfo('https://www.softbank.jp/mobile/support/mail/antispam/email-i/white/', 'SoftBank受信リスト設定');
        } else if ( email.value.match(/docomo.ne.jp/) && emailForm.children.length == 5 ) {
            settingInfo('https://www.nttdocomo.co.jp/info/spam_mail/domain/', 'docomo受信リスト設定');
        } else if ( (email.value.match(/ezweb.ne.jp/) || email.value.match(/softbank.jp/) || email.value.match(/docomo.ne.jp/)) && emailForm.children.length == 6 ) {
            ;
        } else if ( (!email.value.match(/ezweb.ne.jp/) || !email.value.match(/softbank.jp/) || !email.value.match(/docomo.ne.jp/)) && emailForm.children.length == 6 ) {
            document.querySelector('.order-user__form--body--email-warning').remove()
        }
    }
</script>
{% endblock %}

app/templates/app/sctl.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
<title>特定商取引法に基づく表記 | spoon</title>
{% endblock %}

{% block content %}
<h1 class="title">
    <span class="sctl-title px-2 px-sm-3">特定商取引法に基づく表記</span>
</h1>

<ul class="sctl mx-auto p-0">
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">販売業者名</p>
        <p class="sctl__li--text px-4">有限会社プラリネ</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">代表者</p>
        <p class="sctl__li--text px-4">細谷和利</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">販売元</p>
        <p class="sctl__li--text px-4">
            <span class="sctl__li--text--ename d-inline-block">spoon</span>
            ジェラート＆焼菓子
        </p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">所在地</p>
        <p class="sctl__li--text px-4">〒370-0074 <br class="d-sm-none">群馬県高崎市下小鳥町67番地5</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">電話番号</p>
        <p class="sctl__li--text px-4">027-363-8258</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">販売商品</p>
        <p class="sctl__li--text px-4">手づくりジェラート</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">販売価格</p>
        <p class="sctl__li--text px-4">
            <a href="{% url 'order' %}">spoonのお持ち帰り予約</a>
            ページをご覧ください
        </p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">商品代金以外の必要料金</p>
        <p class="sctl__li--text px-4">特になし　<br class="d-sm-none">※料金に消費税を含みます</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">お支払い方法</p>
        <p class="sctl__li--text px-4">店頭にて現金またはPayPayのみの取り扱いとなります</p>
    </li>
    <li class="sctl__li mb-5">
        <p class="sctl__li--heading mb-2 pl-3 py-2">返品・交換・キャンセル等</p>
        <p class="sctl__li--text px-4">商品の性質上、お客様ご都合による返品、交換はいたしかねますのでご了承ください。万が一商品に不良や品違いがございましたら、当日中に購入店舗へ直接お電話にてご連絡ください。交換または返金をさせていただきます。翌日を過ぎますと返品交換のご要望はお受けできなくなりますのでご了承ください。</p>
    </li>
</ul>
{% endblock %}

app/templates/app/sidebar.html
{% load static %}

<div class="sidebar col-xl-3 mt-5 mt-xl-2">
    <div class="sidebar__store d-none d-xl-block text-xl-left">
        <img class="sidebar__store--img" src="{% static 'img/spoon_right.png' %}" alt="spoonお店外観">
        <p class="sidebar__store--name mb-0 mt-1">spoon ジェラート＆焼菓子</p>
        <p class="sidebar__store--info mt-2">
            <a class="sidebar__store--info--map" href="https://www.google.co.jp/maps/place/%E3%80%92370-3522+%E7%BE%A4%E9%A6%AC%E7%9C%8C%E9%AB%98%E5%B4%8E%E5%B8%82%E8%8F%85%E8%B0%B7%E7%94%BA%EF%BC%91%EF%BC%92%EF%BC%94%EF%BC%93%E2%88%92%EF%BC%99/@36.3803438,139.0080042,17z/data=!3m1!4b1!4m5!3m4!1s0x601e8c8d4e95f6e7:0x5882f4339e9e0814!8m2!3d36.3803395!4d139.0101929?hl=ja">群馬県高崎市菅谷町1243-10</a><br>
            営業時間 12:30～17:30 不定休<br>
            <!-- 平　日　12:30～17:30<br> -->
            <!-- 土日祝　11:00～18:00<br> -->
            <!-- 不定休<br> -->
            <span class="help-text">※材料が終わり次第、営業終了になることもございます。</span>
            TEL 027-310-0112<br>
        </p>
    </div>
    <!-- Instaglam -->
    <!-- <div id="insta-window" class="iswd-base p-3 p-sm-5 p-xl-2 mt-xl-5" data-username="spoon_gelato" data-display-image-count="9" data-wrapper-width></div> -->
</div>

{% block extrajs %}
    <!-- <script src="https://insta-window-tool.web.app/v2/insta-window.js"></script> -->
{% endblock %}

app/templates/app/thanks.html
{% extends "app/base.html" %}

{% block content %}
<div class="thanks">
  <p>ご注文ありがとうございました。</p>
  <p>今後ともご愛顧賜りますよう、<br class="d-md-none">お願い申し上げます。</p>
  <a class="btn rounded-pill" href="/" ontouchstart="">
    <i class="fas fa-cart-plus fa-fw" aria-hidden="true"></i>買い物を続ける
  </a>
</div>
{% endblock %}